# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pooria Esmaeili
title: Machine Learning Engineer, Data Scientist
email: pooriaesmaeili96@gmail.com
#website: www.github.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics

github_username:  PooriaEsmaeili
linkedin_username: pooria-esmaeili

# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/pooria.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am a machine learning engineer/data scientist with extensive experience in developing and deploying various AI methods. I have a strong foundation in mathematics and statistics, and I am curious about the applications of machine learning in real-world problems.
  
#  You can check out my full resume <a href="https://drive.google.com/file/d/1Bt6mezC_v-bOkoWQSdPbUXGefUv_8QkD/view?usp=sharing"> <mark>here</mark> </a>.
content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Deep Reinforcement Learning Based Energy Efficient Multi-UAV Data Collection for IoT Networks
  #       link: github.com/sproogen
  #       link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         My Thesis

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Machine Learning Researcher 
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: University of Guelph
        caption: January 2021 - June 2022
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          In my thesis, I integrated a Reinforcement Learning framework into the FPGA placement flow to dynamically choose the best optimization strategy during the detailed placement. I developed several reinforcement learning models, such as Tabular Q-Learning, Deep Q-Learning, and Advantage Actor-Critic models using TensorFlow, to capture different characteristics of each circuit placement and use them in the decision-making process. The proposed framework was able to reduce the runtime by 50% while solution quality is preserved.
      
      - layout: left
        title: Data Scientist
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Tapsi
        caption: April 2019 - December 2020
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Tapsi is a mobility service provider in Iran. I was a part of the data team in the commercial department. Our role was to identify trends and capture insights of customers’ trips in each season using unsupervised and clustering algorithms to offer competitive fares (increased profitability by 3%). Another duty of mine was retrieving data for the weekly trips and publishing interactive dashboards to provide actionable insights using SQL and Power BI.

      - layout: left
        title: Undergraduate Research
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: University of Tehran
        caption: September 2017 - March 2019
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I was focused on fault management in approximate applications, namely the implementation of an RL agent which regulates cache voltage to maintain a suitable trade-off between power and quality using gem5 and McPAT. This agent can be trained using Q-Learning algorithm to decrease power while it monitors the quality of results and does not let it drop below a specific threshold. 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Guelph
        caption: 2021 - 2022
        sub_title: MSc in Computer Engineering
        description: | # this will include new lines to allow paragraphs
          During my master’s, I investigated applications of machine learning in FPGA CAD flow. To broaden my understanding of machine learning and data science, I took several courses including Deep Learning, Reinforcement Learning, and Advance Soft Computing. In my thesis, I applied deep reinforcement learning techniques to the FPGA placement problem.
      - layout: left
        title: University of Tehran
        caption: 2014 - 2019
        sub_title: BSc Electrical Engineering
        description: | # this will include new lines to allow paragraphs
          I started my undergrad studies in electrical engineering. Most of the courses I had to undertake were on theoretical mathematics and statistics, which helped me to form a strong foundation in those areas. Later, as I was fascinated by data-driven algorithms and their applications, I took Machine Learning and Machine Vision courses. In my BSc research, I investigated the application of machine learning algorithms in hardware systems.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
